[package]
name = "tpt-certus-geometry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
description = "3D geometric primitives (Vector3, AABB, Ray, Plane, etc.) for tpt-certus."

[dependencies]
tpt-certus-math = { workspace = true }
tpt-eng-geometry = { workspace = true }
tpt-eng-mesh = { workspace = true }

[lints]
workspace = true